[Fix] - Header and footer links in the newsletter
OpenSourcePolitics/decidim-mel pull request #23
Opened 2023-05-17 08:07 UTC by AyakorK

### Description 

Base images (like header and footer) were not displayed on emails because we had a relative link so when we were asking for /decidim-packs/header in a gmail mail in reality we were asking gmail/decidim-packs/header that obviously does not exist.

#### Tasks

- [x] Change the way we displayed header and footer in template
- [x] Update the Application.rb to just get rid of the final slash to avoid duplications in the url

#### How to test

- First of all you'll need to add to you environment your host (ex: localhost:3000)
- You'll need to check if your protocol is http or https, in the first case you'll need to change the line 27 in your application.rb to get rid of the "s"
- Initialize your app
- Go to newsletters
- Create a new one using the first pattern
- Use your browser console to check if the src of the image is complete (If your url starts with a / that means it doesn't work because you have a relative path.)

2023-05-17 13:49 UTC, Quentinchampenois requested changes
Thank you,

I have some suggestions : 

`image_pack_tag` returns the relative path to the resource, we want to use [Webpacker::Helper#image_pack_url](https://www.rubydoc.info/github/rails/webpacker/Webpacker%2FHelper:image_pack_url). With this helper we can return the absolute url [see source](https://github.com/rails/webpacker/blob/632fb85d6dab874f381b3b4059bba883c5520a46/lib/webpacker/helper.rb#L42). 

We should not edit the `config.action_mailer.asset_host` because it might causes unexpected behaviours.

Also we should add tests to ensure the returned URL is absolute

2023-05-17 13:49 UTC, Quentinchampenois commented on app/cells/decidim/newsletter_templates/mel_template/show.erb
> +              <img src="<%= "#{Rails.application.config.action_mailer.asset_host}#{asset_pack_path('media/images/header_email.png')}" %>" alt="<%= t('alt_banner_image', scope: 'decidim.newsletter_tem
We must use Rails helpers to display images

2023-05-17 13:49 UTC, Quentinchampenois commented on app/cells/decidim/newsletter_templates/mel_template/show.erb
> +            <img src="<%= "#{Rails.application.config.action_mailer.asset_host}#{asset_pack_path('media/images/footer_email_group.png')}" %>" alt="<%= t('alt_banner_image', scope: 'decidim.newsletter
Use rails helper

2023-05-22 16:10 UTC, paulinebessoles approved these changes

2023-05-23 08:10 UTC, Quentinchampenois approved these changes

2023-05-29 12:58 UTC, paulinebessoles approved these changes

2023-05-29 12:58 UTC, merged